build.gradle, src/main/java/uk/gov/ons/ras/collectioninstrument/entities/CollectionInstrument.java
I've switched the CollectionInstrument entity to use Gson instead of Jackson, which makes the implementation less verbose. 
I thought I'd PR this to check we're happy with it.
=> Trying Gson for simpler implementation.

.codecov.yaml, .travis.yml
Update travis.yml file to run codcov after a successful build. Add config file to setup target
=> Add codecov to travis.yml

Procfile, config.ini, requirements.txt, swagger_server/swagger/swagger.yaml
This is to sync up versions from different repo's with common code and gateway
=> Release 0.3 (API gateway compatibility)

scripts/test.sh, swagger_server/controllers/collectioninstrument.py, swagger_server/swagger/swagger.yaml
Relatively trivial label change for JT
=> Changes to search results fot JT

requirements.txt, swagger_server/controllers/ciupload_controller.py, swagger_server/controllers/collectioninstrument.py, swagger_server/controllers/respondent_controller.py
Each request made to an end point should output logs in either standard text or JSON.
* To test log output in JSON, set `log_format = json` in <project_root>/config.ini. 
* To test log output in standard text, set `log_format = text` in <project_root>/config.ini. 
**N.B. Currently, logged output is only on exceptions generated from a request**
=> Tbl 038/align logging format

config.ini
=> Adding CI space

requirements.txt, swagger_server/controllers/helper.py, swagger_server/controllers/survey_response.py, swagger_server/test/test_helper.py, swagger_server/test/test_survey_response.py
To make sure someone isn't trying to land exe files on ONS estate. The code makes use of the python-magic library
Run the test and then on cf try to upload an exe with an xls extension
=> Defect 26 unfiltered file upload

config.ini, swagger_server/controllers/survey_response.py, swagger_server/test/test_survey_response.py
Fixes the file name being wrong.
=> Isu 8 filename correction from a respondent upload

swagger_server/controllers/survey_response.py
Modifying the constant strings to match those given in the error displays found here: https://trello.com/c/13zCNEy7
=> modifying constant file error strings to match designs

Pipfile, Pipfile.lock, application/controllers/collection_instrument.py, application/controllers/cryptographer.py, application/views/collection_instrument_view.py, tests/controllers/test_collection_instrument.py, tests/views/test_collection_instrument_view.py
Two ends were overlooked on the refactor /download/<instrument_id> and /instrument_size/<instrument_id>. This PR reintroduces them
=> Add missing end points and tests

.gitignore, Dockerfile, Pipfile.lock, config/config-docker.yaml, run.py
Can someone take a careful look at the changes in Pipfile.lock - they came about when I did 'pipenv install xlsxwriter' but they don't look right to me ...
=> Re-dockerised ras-collection-instrument service

Pipfile, Pipfile.lock, app.py, application/cloud/cloudfoundry.py, application/schemas/collection_instrument_schema.json, config.py, run.py
Changes to the config and added in the collection instrument schema so that builds now run in jenkins
=> Jenkins config changes

API.md
The API.md file has 2 missing ends points, download and instrument_size. This PR address that
=> Update API.md file

config.py
=> align basic auth

.travis.yml, API.md, Pipfile, Pipfile.lock, alembic.ini, application/controllers/collection_instrument.py, application/controllers/helper.py, application/models/models.py, application/views/collection_instrument_view.py, config.py, docker-compose.yml, migrations/README, migrations/env.py, migrations/script.py.mako, migrations/versions/72912058602c_remove_classification_table_and_add_.py, run.py, tests/controllers/test_collection_instrument.py, tests/controllers/test_helper.py, tests/views/test_collection_instrument_view.py
**Scope**
We need to be able to upload non BRES SEFT surveys, and to achieve this we must be able to
1. Upload with RU
2. Upload without RU
3. Upload with dynamic classifiers
4. Search with dynamic classifiers
5. Limit the search results in date order (most recent first)
**How to test**
The best way to test, is run the application (pipenv run python run.py) If you do this, you will need to update the config file so it points to a valid survey and exercise services. Additionally you will need to set a ONS_CRYPTOKEY (export ONS_CRYPTOKEY='anything')
Once up and running you should be able to **POST** to the end points with a **file**.
1. Upload with RU
http://0.0.0.0:8002/collection-instrument-api/1.0.2/upload/14fb3e68-4dca-46db-bf49-04b84e07e77c/999
2. Upload without RU …
=> CI Service - needs functionality to be able to upload a non-BRES SEFT Survey.

application/controllers/basic_auth.py, application/views/collection_instrument_view.py, application/views/survey_responses_view.py, tests/views/test_collection_instrument_view.py, tests/views/test_survey_response_view.py
The Basic Auth was missing from collection instrument, this implements it and adds some tests
=> Add Basic Auth to collection instrument

application/cloud/cloudfoundry.py
The lookup should be on name and not label and should be ras-ci-db
=> Update lookup on cf database

run.py
Retry database connection on DatabaseError every 2s for up to 30s. This
allows the app to be more robust when starting up. For instance when
running up apps via docker-compose the app should be able to recover
if the database is not up first.
=> Add resilience to database errors or non-existence

application/controllers/collection_instrument.py, application/controllers/service_helper.py, run.py
Updating logging to conform with SDC standards
=> update logging standards

application/controllers/collection_instrument.py
Tiny addition of an "action" field to the published JSON.
=> Add context to the rabbitmq upload message

application/controllers/collection_instrument.py, application/models/models.py, migrations/versions/ccd22863e633_create_seft_instrument_table.py, tests/controllers/test_collection_instrument.py, tests/views/test_collection_instrument_view.py
Migrating data associated to a SEFT CI file into it's own table.
https://trello.com/c/QharabAR/42-us029-int-select-load-eq-collection-instruments-xxl
=> Us029 restructure databse

application/models/models.py
Required for US062: EXT - Access an eQ
=> Add type to collection instrument

config.py
=> Upping to version 1.2.2

Pipfile, Pipfile.lock, config.py, run.py
This reverts commit 53aee05260d1f187ef230c16fe86dac78cb7c27c.
=> Revert "ZipKin Tracing (#126)"

Pipfile, Pipfile.lock, config.py, run.py
Reintroduce #126 with the pipenv gevent fix.
=> Zipkin + pypa/pipenv#2113 fix

application/logger_config.py
Add Zipkin trace IDs to the logs
Configuration
Run unit tests and acceptance tests, examine logs for Zipkin IDs
=> Add Zipkin trace IDs to logs.

application/logger_config.py
Align trace names in logs with Java services.
=> Align trace naming in logs with other services.

.travis.yml
Image name is not consistent across travis, pom files etc...
build & push image as "eu.gcr.io/census-rm-ci/rm/census-rm-collectioninstrumentsvc"
**1.** check out branch
**2.** create a temporary commit by adding the following to .travis.yml file (before "- bash <(curl -s https://codecov.io/bash)" line) in "after_success:"  - 
```
- if [ "$TRAVIS_BRANCH" == "image-location-change" ] ; then
docker login -u "${DOCKER_GCP_USERNAME}" -p "${DOCKER_GCP_PASSWORD}" "${DOCKER_GCP_REGISTRY}";
docker build -t "$DESTINATION_IMAGE_NAME" .;
docker tag "eu.gcr.io/census-rm-ci/rm/census-rm-collectioninstrumentsvc" "eu.gcr.io/census-rm-ci/rm/census-rm-collectioninstrumentsvc:test";
docker push "eu.gcr.io/census-rm-ci/rm/census-rm-collectioninstrumentsvc:test";
fi
```
and replace "branches" section with - …
=> Image location change

config.py
Bump version to 1.3.4 for release to pre-prod
=> Update version to 1.3.4

Pipfile.lock, application/controllers/service_helper.py
Some of the logging in this repo is at debug level when it should be at info so we can actually see it in the splunk logs.  This PR fixes that, and also updates the packages as it was being done for other repos around the time of the werkzeug security issue.
- Several log lines have been set to info from debug
- A few packages have had minor upgrades
Unit and acceptance tests pass
=> Improve logging and update packages

_infra/helm/values.yaml
Remove CPU requests as the request was far too high
=> remove cpu request

_infra/helm/collection-instrument/templates/deployment.yaml, _infra/helm/collection-instrument/values.yaml
=> added database configuration

_infra/docker/Dockerfile
=> Fix gunicorn start cmd docker

_infra/helm/collection-instrument/templates/service.yaml, _infra/helm/collection-instrument/values.yaml
=> add target port

.travis.yml, Makefile, _infra/docker/Dockerfile
Disabled 'pipenv check' in Makefile, pending resolution of blocking pipenv bugs 2412 (plus duplicates) and 4147
Commented the line 'pipenv check' in the Makefile, with a note to uncomment as soon as possible.
https://trello.com/c/3ZxIpfsX
=> temporarily disabled pipenv check, pending pipenv bug resolution

_infra/helm/collection-instrument/templates/deployment.yaml, _infra/helm/collection-instrument/templates/secret.yaml, _infra/helm/collection-instrument/values.yaml
=> Adding K8 config for Rabbit MQ

_infra/helm/collection-instrument/templates/deployment.yaml
=> Fix kubernetes deployment

_infra/helm/collection-instrument/templates/deployment.yaml
=> Fix Rabbit MQ config map name

_infra/helm/collection-instrument/templates/deployment.yaml
=> Quote SDX config

_infra/helm/collection-instrument/templates/deployment.yaml
=> Add missing port for case service

_infra/helm/collection-instrument/values.yaml
The service port needed to be changed to 8080.
Changed service port to 8080.
[Trello card](https://trello.com/c/iBBXBpLll)
=> changed service port

_infra/spinnaker/deployment-full.json
=> add missing variables

_infra/helm/collection-instrument/templates/deployment.yaml
=> SDX correct kubernetes config

Pipfile, Pipfile.lock, README.md, config.py
=> Updated readme and removed unhelpful default in config

Makefile, _infra/helm/collection-instrument/Chart.yaml
Uncommented pipenv check that was toggled off in previous hotfix for pipenv bugs
make test
https://trello.com/c/3ZxIpfsX
https://github.com/ONSdigital/ras-collection-instrument/pull/161
=> restored pipenv check to Makefile

.github/workflows/comment.yml, .github/workflows/main.yml, _infra/helm/collection-instrument/Chart.yaml
=> Make dev docker tag changes

README.md, _infra/helm/collection-instrument/Chart.yaml, application/controllers/basic_auth.py, application/controllers/collection_instrument.py, application/controllers/cryptographer.py, application/controllers/helper.py, application/controllers/json_encrypter.py, application/controllers/rabbit_helper.py, application/controllers/service_helper.py, application/controllers/session_decorator.py, application/controllers/survey_response.py, application/models/models.py, application/views/collection_instrument_view.py, tests/controllers/test_helper.py, tests/views/test_collection_instrument_view.py
Needs fixing:
- Add collection instrument, delete it then add again.  Marks it as duplicate
=> Handle duplicate BRES collection exercises

_infra/helm/collection-instrument/Chart.yaml, _infra/spinnaker/deployment-full.json
=> syncronize default helm chart

_infra/helm/collection-instrument/Chart.yaml, application/models/models.py
=> Lazy load seft data files

.github/workflows/main.yml, _infra/helm/collection-instrument/Chart.yaml, _infra/spinnaker/prodDeploy.json
Update needed to hash in production pipeline, to use template with release parameters.
Also updated GH Actions to ignore Spinnaker changes in build trigger.
- https://collaborate2.ons.gov.uk/jira/browse/RAS-141
=> update SHA in prod template, exclude spinnaker from GH triggers

.github/workflows/comment.yml, _infra/helm/collection-instrument/Chart.yaml
=> change from sandbox to dev

_infra/helm/collection-instrument/Chart.yaml, _infra/helm/collection-instrument/templates/deployment.yaml, _infra/helm/collection-instrument/values.yaml
=> add proxy resource requests for collection instrument

_infra/helm/collection-instrument/Chart.yaml, _infra/helm/collection-instrument/templates/hpa.yaml, _infra/helm/collection-instrument/values.yaml
=> add min replicas

_infra/helm/collection-instrument/Chart.yaml, _infra/helm/collection-instrument/templates/deployment.yaml, _infra/helm/collection-instrument/templates/externalsecrets.yaml, _infra/helm/collection-instrument/values.yaml
=> add external secrets

.github/workflows/comment.yml, _infra/helm/collection-instrument/Chart.yaml
Use new github action created specifically for ras-rm pr comments.
https://github.com/ONSdigital/ras-rm-spinnaker-action
=> new comment action

_infra/helm/collection-instrument/Chart.yaml, application/controllers/session_decorator.py, config.py
Logging should be at a high level so you can filter it after the fact if you need it.  It was previously not showing ANY debug logging.  This sorts that.
Also removed a few log lines that would never ever be useful and were just noise.
=> Default logging to debug and remove useless logs

.github/workflows/main.yml, Dockerfile, Pipfile, Pipfile.lock, _infra/helm/collection-instrument/Chart.yaml, tox.ini
Upgrades python from 3.8 to 3.9 to keep it current
=> Upgrade python to 3.9

.github/workflows/main.yml, _infra/helm/collection-instrument/Chart.yaml, app.py
Also an attempt at fixing the Github Action issues
=> Change master to main

README.md, _infra/helm/collection-instrument/Chart.yaml
=> Remove badges

_infra/helm/collection-instrument/Chart.yaml, application/controllers/collection_instrument.py, application/controllers/helper.py, application/views/collection_instrument_view.py, tests/controllers/test_collection_instrument.py, tests/views/test_collection_instrument_view.py
=> Add patch endpoint for file

_infra/helm/collection-instrument/Chart.yaml, application/controllers/collection_instrument.py, application/views/collection_instrument_view.py, tests/views/test_collection_instrument_view.py
=> Fix bug with file upload

Pipfile.lock, _infra/helm/collection-instrument/Chart.yaml
One of the packages, urllib3, has a security vulnerability.  This updates that package and the others at the same time.
=> Update packages to fix security vulnerability

_infra/helm/collection-instrument/Chart.yaml, _infra/helm/collection-instrument/templates/deployment.yaml
=> Fix indentation in chart

_infra/helm/collection-instrument/Chart.yaml, application/logger_config.py
=> Have stack trace printed in logs

Pipfile.lock, _infra/helm/collection-instrument/Chart.yaml, application/controllers/gcp_survey_response.py
=> Fix md5 hash

.github/workflows/main.yml, Pipfile.lock, _infra/helm/collection-instrument/Chart.yaml
During the release step tag the generated docker image as both the release version and latest.
=> Docker tag latest at the same time as the release

_infra/helm/collection-instrument/Chart.yaml, _infra/helm/collection-instrument/templates/deployment.yaml
=> Update sql proxy from 1.16 to 1.22

_infra/helm/collection-instrument/Chart.yaml, _infra/helm/collection-instrument/templates/deployment.yaml, application/controllers/gcp_survey_response.py, config.py, tests/controllers/test_gcp_survey_response.py
=> Add specific project for seft pubsub

Pipfile.lock, _infra/helm/collection-instrument/Chart.yaml
=> Upgrade packages

_infra/helm/collection-instrument/Chart.yaml, application/controllers/gcp_survey_response.py, tests/controllers/test_gcp_survey_response.py
remove json wrapper from message
S33 GPG Encryption For SEFT responses
=> remove json wrapper gnu seft - DRAFT

_infra/helm/collection-instrument/Chart.yaml, application/controllers/gcp_survey_response.py
https://trello.com/c/Yuj6r1GI/651-s33-gpg-encryption-for-seft-responses
=> add .gpg extension

_infra/helm/collection-instrument/Chart.yaml, application/controllers/survey_response.py, application/views/survey_responses_view.py
https://trello.com/c/sxaEe7B0/872-ritm0646854-file-name-too-long-issue-on-fsps-for-respondents-trying-to-upload-survey
=> Additional logging against file validation

Pipfile, Pipfile.lock, _infra/helm/collection-instrument/Chart.yaml, _infra/helm/collection-instrument/values.yaml
=> Unpin pubsub package and upgrade all

.github/workflows/main.yml, Dockerfile, Pipfile, Pipfile.lock, _infra/helm/collection-instrument/Chart.yaml, tox.ini
=> Upgrade to Python 3.10

application/controllers/gnu_encryptor.py, config.py
Logs filling up with unnecessary and potentially info we don't want to show 
log seft file
https://trello.com/c/XsE6zCNP/1233-surpress-logging-for-encrypted-collection-instrument
=> Change log level

.github/workflows/comment.yml, .github/workflows/main.yml, _infra/helm/collection-instrument/Chart.yaml
=> Update workflows to v0 version

_infra/helm/collection-instrument/Chart.yaml, _infra/helm/collection-instrument/values.yaml
Changing the default dev value from gcp.project to be in line with the rest of our services
=> Changing default project to sandbox

.github/workflows/main.yml, Makefile, _infra/helm/collection-instrument/Chart.yaml
Removal of deprecated github action
https://trello.com/c/JyPxSmDA/2298-replace-soon-to-be-deprecated-set-output-in-github-actions
=> Fix setoutput

Pipfile, Pipfile.lock, _infra/helm/collection-instrument/Chart.yaml, application/controllers/collection_instrument.py, application/exceptions.py, application/logger_config.py, application/models/models.py, application/views/info_view.py, run.py, tests/controllers/test_helper.py, tests/controllers/test_service_helper.py, tests/views/test_collection_instrument_view.py, tests/views/test_info_view.py
=> Raise error if ru specific instrument uploaded

_infra/helm/collection-instrument/Chart.yaml, application/controllers/collection_instrument.py, application/views/collection_instrument_view.py, tests/controllers/test_collection_instrument.py, tests/views/test_collection_instrument_view.py
=> Allow for deletion of EQ collection instruments

Pipfile.lock, _infra/helm/collection-instrument/Chart.yaml
This PR update flask to 2.3.2
Make sure collection instrument service still works
=> RAS-805 update flask to 2.3.2

.github/workflows/main.yml, _infra/helm/collection-instrument/Chart.yaml
Replacing the unmaintained create release action with a github command that does the same and updating the setup-gcloud
Check the build
https://jira.ons.gov.uk/browse/RAS-1011
=> RAS-1011 Replace unmaintained actions/create-release and update google-github-actions/setup-gcloud

Pipfile.lock, _infra/helm/collection-instrument/Chart.yaml
Update gunicorn to 23.0.0
Ensure collection instrument works
[RAS-1259](https://jira.ons.gov.uk/browse/RAS-1259)
=> Updating gunicorn to 23.0.0

_infra/helm/collection-instrument/Chart.yaml, _infra/helm/collection-instrument/values.yaml
Testing disabling load balancer
[Card](https://jira.ons.gov.uk/browse/RAS-1352)
=> disable load balancer
