ONSdigital/ras-collection-instrument

setup.cfg

Change the max length for pep8 checks from 80 characters per line to 160

Change pep8 line length to 160

---

swagger_server/controllers/submitter/encrypter.py

These need to be set now as SDX is using the new crypto lib which assumes the KIDs are present in both the JWT and JWE headers

Seting Key identifiers for RAS encrypter

---

swagger_server/controllers/collectioninstrument.py

Set the survey id on instrument rather than appending instrument  to the list on survey, as that causes the whole instrument table to be loaded into memory which in turns crashes the application as the table contains large binary blobs.

Fix out of memory error during file upload

---

requirements.txt
swagger_server/controllers/survey_response.py
swagger_server/test/test_survey_response.py

**THIS PR NEEDS FURTHER DISCUSSION BEFORE BEING MERGED. THIS IS A POTENTIAL OPTION IF NEEDED**
Python magic is not working as expected, some files are being identified as being Zip archive data when they are of type xls. This will stop uploading of file. This PR remove the python-magic code

Remove Python-magic

---

manifest.yml

Add manifest file for cloudfoundry deployments
1. Are the defaults set to sensible values?
1. Are we missing any manifest properties that should be there?
1. Could we strip them down further?

Add manifest for cloudfoundry deployments

---

application/views/collection_instrument_view.py

Small fix to stop collection instrument size endpoint returning `\n` at the end of responses.
We were jsonifying the string when we didn't need to

Return instrument size as string without \n

---

application/views/info_view.py
tests/views/test_info_view.py

Request from Tech lead to add details to the info end point to align with other services. Currently deployed to http://ras-collection-instrument-dev.apps.devtest.onsclofo.uk/info if a visual check is need.

Add info details to view

---

config.py

The config in collection instrument missed the RABBITMQ_AMQP env and hardcoded it to something that wouldn't work. This allows Jenkins to now inject it in cloud foundry

Update rabbitmq env 

---

Pipfile
Pipfile.lock

`pipenv check` spots a vulnerability defined here
https://www.cvedetails.com/cve/CVE-2013-7459/. A stackoverflow post
suggests pycryptodome is a drop in replacement for pycrypto
https://stackoverflow.com/questions/41813030/problems-with-installation-pycrypto-in-python-3-6

Use pycryptodome instead of pycryto

---

application/controllers/collection_instrument.py

We are currently re-querying collection instrument for no reason, this PR removes that and tidies up the variables to make it easier to read

Stop re-query of collection instrument in search

---

application/controllers/collection_instrument.py
application/views/collection_instrument_view.py
tests/views/test_collection_instrument_view.py

Ru ref is being used for both the download instrument and download csv end points. Now we have moved to collection instruments without Ru ref we need to change this to file_name.

TBL 127 Remove the Ru reference on download

---

application/controllers/survey_response.py
application/logger_config.py

Imports publisher from sdc rabbit app module rather than publisher file protects against name changes in the repo. Also use stdout for application logging rather than stderr.

Use stdout for logging

---

app.py
application/controllers/collection_instrument.py
application/controllers/rabbit_helper.py
run.py
tests/controllers/test_collection_instrument.py
tests/controllers/test_survey_response.py

The rabbitmq instance may not yet be ready to accept connections when the collection instrument service is started. This retries the initialisation steps (and therefore the connection to the provided rabbitmq URL) repeatedly until it fails (similar to init for the database).

US042 Add retry for rabbitmq initialisation

---

API.md
application/views/collection_instrument_view.py
tests/views/test_collection_instrument_view.py

To decouple the collection exercise from the known number of associated CI's, it is necessary to add a `/count` endpoint to the collection instrument (this) service.

US042 Add endpoint for returning count of collection instruments

---

Jenkinsfile
application/controllers/rabbit_helper.py
config.py

Collection instrument needs to be able to get to 2 different rabbit instances, one for the response uploads and a different one for collection instruments upload

Use multiple rabbit instances

---

application/controllers/collection_instrument.py
tests/views/test_collection_instrument_view.py

Search string for classifier FORM_TYPE will be caps but the 'form_type' classifier is stored lowercase. This PR allows to search using upper case FORM_TYPE for classifier 'form_type'.

Search FORM_TYPE classfier with lowercase

---

application/controllers/collection_instrument.py
application/views/collection_instrument_view.py
tests/views/test_collection_instrument_view.py

As a: CEC
I need: to be able to remove a  loaded SEFT CI
So that: the correct CI is associated to the RU 
https://trello.com/c/LhzrsVoU/69-us059-remove-seft-loaded-ci-s

Add unlink exercise endpoint

---

Pipfile.lock

The hash of pluggy 0.6.0 has been incorrectly updated, causing a build failure with a fresh virtual environment. This PR updates the hash to match the remote ones. 
See https://github.com/pytest-dev/pluggy/issues/135
and
https://github.com/ONSdigital/ras-secure-message/pull/190

Update pluggy 0.6.0 hashes as they've been changed

---

Procfile
config.py

Performance Improvement
- Changing Gunicorn `sync` workers from 4 to 8.
- Requires 512M instance on cloud foundry environments.
- Incrementing version for release.
Has been load tested in Prunes. Just check the deployment pipeline is green after the changes are merged to `master`.
NA

Performance improvement 650 concurrency

---

API.md

The endpoint listed in API.md for linking collex is wrong. This fixes that!

Removing lies from API.md

---

application/controllers/collection_instrument.py
application/views/collection_instrument_view.py
tests/controllers/test_collection_instrument.py
tests/views/test_collection_instrument_view.py

We were seeing intermittent issues where collection exercises would
fail to be set into `ready for live` state. We observed in the logs that
collection instrument counts from the collection exercise service was 0
after collection instrument had said it have saved a collection
instrument. This was likely because collection exercise processed the
message before the data changes were committed to the database. This change publishes the message after the data has been saved. The
downside to this is that if a message failed to publish then the data
would not be rolled back. To manage this scenario we log at error level
with relevant information
The theory of the issue
1. Upload collection instrument (CI service) - https://github.com/ONSdigital/ras-collection-instrument/blob/master/application/v …

Publish message after transaction

---

Pipfile
Pipfile.lock
config.py
run.py

Motivation and Context
==
Currently there's no way to trace the requests through the application.
What Changed
==
This will add the tracing headers to any request that comes through this
application onto another service, or preserve existing headers allowing
the user to follow requests through the application as a whole.
There are also new configuration settings:
```
| ZIPKIN_DISABLE                  | Totally disable Zipkin (including tracing headers)            | False
| ZIPKIN_DSN                      | Zipkin Sample API URL (e.g. http://zipkin:9411/api/v1/spans)  | None
| ZIPKIN_SAMPLE_RATE              | Percentage of requests to send to zipkin span API             | 0
```
By default this will add the tracing headers, but make no requests to
Zipkin's neat little UI.
How to test
==
No …

ZipKin Tracing

---

.travis.yml

We want travis build to push docker images to Google Container Registry instead of dockerhub
Replaced docker image prefix with GCR registry location
NOTE: before merge, remove "automate-census-docker-build" branch condition in .travis.yml file
From travis dashboard, switch to  "automate-census-docker-build" branch and "Restart Build". Once complete, check latest Docker image is in GCR.
[Trello](https://trello.com/c/SLBH8XU6/468-create-travis-build-files-for-non-java-github-repos)

Automate census docker build

---

README.md
application/views/info_view.py
config.py

This application has a configurable name and version.  These aren't things that should be configured on deploy.
The single use of NAME is now hardcoded in the info endpoint.  The configurable version is now hardcoded in the config file.  Updated the readme to show all the configurable items.  The readme has also had its linting issues fixed
- Unit tests pass
- Check preprod and prod deployment to make sure NAME and VERSION aren't being set.  If they are, remove them.
https://trello.com/c/rao67UDS/1011-remove-application-name-config-item-environment-variable-from-ras-repos-3

Remove configurable name and version.  Updated readme

---

Pipfile.lock
application/controllers/rabbit_helper.py

sdc-cryptography has a new version that we should be using.
- Packages updated with `pipenv lock`, resulting in a number of packages being updated as well as the one we specifically wanted. 
- `rabbit_helper.py` changed to remove an arguement that was removed as part of the upgrade to sdc-rabbit 1.6.0 (which came as part of the above step)
Unit and acceptance tests pass
https://trello.com/c/hmQQabr6/1092-all-sdx-ras-repos-to-use-the-latest-version-of-sdc-cryptography-iv3

Update packages and fix rabbit helper

---

Jenkinsfile
README.md
application/controllers/service_helper.py
config.py

This change sets all the environment variables consistent across all the services to alleviate confusion when adding new functionality. This will also remove confusion for migration.
All environment variables that have the prefix RM or RAS the prefix has been removed.
Run the tests as normal using make test to ensure no tests have been broken through the renaming process.
https://trello.com/c/3FBH3nNx

updating env vars to be consistent

---

_infra/helm/collection-instrument/Chart.yaml
_infra/helm/collection-instrument/templates/deployment.yaml
_infra/helm/collection-instrument/values.yaml

Adds kube_dns addresses for all connecting services to allow us to have circular references

Create DNS entries for each service

---

_infra/helm/collection-instrument/Chart.yaml
_infra/helm/collection-instrument/templates/deployment.yaml
_infra/helm/collection-instrument/values.yaml

Allowing the selection of different version numbers will allow code changes to be tasted without needing to commit to master.
- Added if-statement in `deployment.yaml` to select version number based on the presence of the `latest` tag in `values.yaml`.
- Updated chart version number.
- Added `latest` tag to `values.yaml`.
[Trello card](https://trello.com/c/Xlj2T6Gi)

Variable version number

---

_infra/helm/collection-instrument/templates/deployment.yaml
_infra/helm/collection-instrument/values.yaml

The helm charts needed to have the option of selecting different repos when a developer is testing changes.
- The `deployment.yaml` now switches to the devRepo if the `latest` tag is not set.
- Added the devRepo to `values.yaml`. As of now, it is the same as the current image's repo, but will be different in prod and pre-prod.
[Trello card](https://trello.com/c/fLbRN0qG)

added devRepo

---

_infra/helm/collection-instrument/Chart.yaml
_infra/helm/collection-instrument/templates/deployment.yaml
_infra/helm/collection-instrument/values.yaml

Update Helm chart with a flag to determine if the SDX rabbit cluster is external.
In preprod and prod the rabbit cluster used for RASRM-SDX traffic is external and hosted outside of our kubernetes cluster, so we need to use different connection details.
In the performance environment, we need to use the same Rabbit cluster in the rabbit namespace for RASRM-SDX that RASRM uses for internal communication.
All other environments will use a Rabbit service deployed in their own namespace.

Add flag to determine if SDX cluster is external

---

_infra/helm/collection-instrument/Chart.yaml
application/logger_config.py

Added "severity level" processor to structlog, so Google Cloud Logging can parse severity
New structlog processor defined in logger config, replacing obsolete zipkin processor
locally: pipenv run tox
dev: Spin up cluster in Dev, with pod built from image tag "cloud-logging"; generate error; check Stackdriver logs for correct parsing and severity levels
https://trello.com/c/wDSxYgCQ

Add structlog processor for Google Cloud Logging

---

_infra/helm/collection-instrument/Chart.yaml
application/controllers/collection_instrument.py
tests/views/test_collection_instrument_view.py

Previously there weren't any checks to make sure that duplication wasn't happening when uploading collection instruments (especially around EQ).  This adds a check so  if you're uploading an instrument for a survey only, and ALL the collection instruments are the same then it'll raise an error as it's a duplicate

Add duplicate classifier protection

---

.github/workflows/comment.yml
.github/workflows/main.yml
_infra/helm/collection-instrument/Chart.yaml

Replacing set-env command in GH Actions, disabled this week for security reasons
- https://trello.com/c/5Pj2VUx5

replace deprecated cmd in GitHub Actions

---

_infra/helm/collection-instrument/Chart.yaml
config.py

Even though the flag was set to false, it was set to the string 'false' which python evaluates to a truthy value.  This makes it so the strings of true and false will always give the correct boolean value

Update config value to always be boolean value

---

_infra/helm/collection-instrument/Chart.yaml
run.py

Unit tests are failing due to deprecated method in flask.
should be able to test locally and in own namespace
https://trello.com/c/0uQlMX9V/735-s38-remove-deprecated-call-to-function-in-ras-collection-instrument

remove app.ctx DO NOT MERGE

---

.github/workflows/main.yml
_infra/helm/collection-instrument/Chart.yaml

Looking at Chart.yaml and the Helm template it contains, apparently we should be incrementing the chart version any time we increment the app version.
This adds auto-increment to the chart version if it hasn't been updated, same as the app version. If the app version has been manually updated but the chart version hasn't been, it'll take the app version as the main source of truth (as this is the one we're most likely to manually update)
This change tests itself on PR :)
https://trello.com/c/j0nYtZ5o/758-update-chart-version-at-the-same-time-as-the-app-version

Update chart version automatically

---

Makefile
_infra/helm/collection-instrument/Chart.yaml
application/views/collection_instrument_view.py
openapi.yaml
tests/views/test_collection_instrument_view.py
tox.ini

The `/instrument_size/{instrument_id}` endpoint isn't used by anything so it can be removed.
Acceptance tests pass?

Remove unused endpoint

---

_infra/helm/collection-instrument/Chart.yaml
application/views/collection_instrument_view.py
openapi.yaml
tests/views/test_collection_instrument_view.py

The collection instrument api had a weird `/collectioninstrument/id/<id>` endpoint to get the collection instrument and should be replaced with a simpler `/<id>` endpoint (like we do for PATCH).  This PR adds the shortened version (whilst leaving the  original for backwards compatibility), updates the API docs and the tests to reflect this change.

Modify api and update docs and tests

---

Makefile
Pipfile.lock
_infra/helm/collection-instrument/Chart.yaml
_infra/helm/collection-instrument/values.yaml
tests/views/test_collection_instrument_view.py

There was an extra 0 in the limit, making have a limit of 3.8 vCpus instead of .38 of a vCpu.
As part of this PR, we've had to comment out pipenv check temporarily as sqlalchemy-utils has an issue but upgrading to the latest doesn't fix it like it usually would.  In the future we'll have to upgrade to whatever the 'fixed' version is, once it's out, and then uncomment pipenv check

Remove extra 0 in limit

---

.github/workflows/comment.yml
.github/workflows/main.yml
_infra/helm/collection-instrument/Chart.yaml

This PR updates Github actions to fix "service_account_key" has been deprecate. Replacing it with google-github-actions/auth in both main.yml and comment.yml
For main.yml check https://github.com/ONSdigital/ras-collection-instrument/runs/7210863053?check_suite_focus=truee
For comment.yml see https://github.com/ONSdigital/response-operations-ui/pull/747 on how I tested in response-operations, as it is a virtual copy bar the service I didn't repeat it here

Fix security account key deprecation

---

_infra/helm/collection-instrument/Chart.yaml
application/controllers/collection_instrument.py
application/models/models.py
migrations/versions/497436b61d0c_remove_seft_data_column.py
tests/views/test_collection_instrument_view.py

This removes the data column in the SEFT table, as this is now being stored in buckets.
https://trello.com/c/0a1C3Vb0/1499-delete-encrypted-instruments-from-collection-instrument-database

Remove seft data column

---

Dockerfile
Pipfile.lock
_infra/helm/collection-instrument/Chart.yaml
application/controllers/collection_instrument.py
tests/views/test_collection_instrument_view.py

The BRES collection exercise was slow to load as it's the only one that's had to load 2.5k instruments.  This highlighted some inefficiencies in the code.  One thing that was noticed was that there is an inefficient call to get the ru_ref and collection exercise ids and add it to the payload.   After looking at all the calls in the system, it was concluded that nothing actually uses this data so we'll leave it blank as it makes a 2.5k instrument exercise go from 25 seconds to load down to 10 seconds.
If it passes our testing and goes live, then we can do another pass to remove the 'classifier' key entirely from the returned dictionary.
- Deploy PR to environment
- Run acceptance tests to seed data
- Create, set ready for live and sign up for the following collection exercises with …

Remove ru_ref and collection_exercise data from classifiers in /collectioninstrument endpoint

---

.github/workflows/main.yml
Dockerfile
Makefile
Pipfile
Pipfile.lock
_infra/helm/collection-instrument/Chart.yaml
tox.ini

Upgrades python to 3.11 and upgrades the github checkout and setup-python versions to more recent versions.

Upgrade python version to 3.11 and actions version

---

_infra/helm/collection-instrument/Chart.yaml
application/controllers/collection_instrument.py

For the multimode changes we need to find out the explicit type of survey, this just adds it to the payload. It also adjusts the filename check to just be SEFT, eQ doesn't have filenames and when there are both eQ and SEFT CIs associated to a CE this would fall over without it
To test in conjunction with https://github.com/ONSdigital/response-operations-ui/pull/833

Add type to collection instrument type

---

_infra/helm/collection-instrument/Chart.yaml
application/controllers/collection_instrument.py
application/controllers/service_helper.py
application/controllers/sql_queries.py
application/exceptions.py
application/views/collection_instrument_view.py
openapi.yaml
tests/controllers/test_service_helper.py
tests/views/test_collection_instrument_view.py

This PR validates if a collection instrument can be uploaded according to it's form_type. 
Test with this PR deploy as well https://github.com/ONSdigital/response-operations-ui/pull/844
Using this PR create a EQ_AND_SEFT survey in rops, upload an eQ form_type (i.e 0001) then try to upload a SEFT using the same form type (a file named 064_201803_0001 would do it), it should return a warning. Repeat the process but the other way around Upload a SEFT first then an eQ. This is survey wide, so try across CE as well (i.e create a CE and upload a eQ, then in a different CE try to add a SEFT with the same form_type)

Add collection instrument form type check eq and seft

---

Pipfile.lock
_infra/helm/collection-instrument/Chart.yaml
application/controllers/collection_instrument.py
application/views/collection_instrument_view.py
tests/views/test_collection_instrument_view.py

As part of the rOps redesign, a new endpoint was required that would allow for a user to add and remove CIs in one go via the rOps CI page. This endpoint deals with both adding and removing CIs in one database transaction. Any failures will roll back the changes and the offending action (add or remove) will be reported to the user. 
Add and remove CIs in rOps. 
Run the unit tests
Run acceptance tests
Trello
https://trello.com/c/ELDnXWO2/2344-rops-design-improvements-ci-page-redesign
Jira
https://jira.ons.gov.uk/browse/RAS-266

Collection Instrument page redesign

---

_infra/helm/collection-instrument/Chart.yaml
application/controllers/collection_instrument.py
application/exceptions.py
application/models/google_cloud_bucket.py
application/models/models.py
application/views/collection_instrument_view.py
tests/controllers/test_collection_instrument.py
tests/views/test_collection_instrument_view.py

This PR adds an end point to delete the collection exercise and associated collection instruments on GCP
N.B 
1. As discussed in tech because of the many to many relationship between exercise and collection instruments and the state of data in PROD I can't add a cascade to exercise to remove all CIs' associated with it. This will not stop CIs' being deleted from GCP, but it will leave CI orphans in the db. This is being tackled when the CI registry is introduced when CE will be a one to many relationship
2. I have been a lot more robust with tests and error catching then how the current repo is written, however stopped short of tackling the issues with  _with_db_session_  Realistically we should have error catching and tests on all these session updates but the decorator needs a fair …

RAS-284 Delete collection instruments by ce id

---

_infra/helm/collection-instrument/Chart.yaml
_infra/helm/collection-instrument/templates/hpa.yaml

Update autoscaling from v2beta2 to v2
The HPA change has already been proven here https://github.com/ONSdigital/ras-party/pull/389, but can be done again if required, just deploy via helm

Update HPA to v2

---

_infra/helm/collection-instrument/Chart.yaml
application/controllers/collection_instrument.py
application/controllers/service_helper.py
application/models/models.py
application/views/collection_instrument_view.py
tests/controllers/test_collection_instrument.py
tests/controllers/test_service_helper.py
tests/views/test_collection_instrument_view.py

This PR fixes the bug associated with the ready for live button not appearing after initially adding a collection instrument. I have also done some refactoring and tidying of the code connected to the problem
Deploy all 3 PRs, this one,  https://github.com/ONSdigital/rm-collection-exercise-service/pull/312 and https://github.com/ONSdigital/rm-collection-exercise-service/pull/312 Now on rops create an eq CE (SEFT will work for add as well, see below for bug on remove) and enter all details bar the CI. Now enter the CI and attach that CI, notice when you hit done the ready for live button appears. Go back in and remove the CI, notice it is gone
N.B there are 2 bugs
1. with EQ_AND_SEFT the current eQ adding code will remove SEFT instruments as well, a card has been create for this
2. Remove …

RAS-728 Fix issue with ready for live button

---

_infra/helm/collection-instrument/Chart.yaml
_infra/helm/collection-instrument/templates/deployment.yaml

This PR adds a wait time for cloud_sql_proxy and stops verbose logging. Currently we deploy the app with a side car cloud_sql_proxy container to access the db. However when a pod is redeployed and the proxy container is sent a SIGTERM the container does not close down gracefully and will kill all connections instantly (i.e sql queries). This naturally gets passed back up the chain to the respondent who will get an error. With us currently using a default pool of 5 and overflow of 10, it means anything up to 15 respondents could get an error when we deploy a new release to prod, which ain't good.
It almost certainly is the reason we see hanging queries and spikes on rollouts in Grafana. This PR adds a term_timeout which will allow the proxy to complete it's query (at least give it 30 …

RAS-850 Cloud sql proxy term timeout and verbose

---

.github/workflows/comment.yml
.github/workflows/main.yml
Pipfile.lock
_infra/helm/collection-instrument/Chart.yaml

This PR replaces set-output within the .github workflow file with environment variables to fix a deprecation with set-output. It also updates actions/auth to v2.
Pipfile has also been updated to resolve werkzeug vulnerability, flask 3 is included.
Check the github builds for any deprecation warnings and ensure everything functions as intended.
https://jira.ons.gov.uk/secure/RapidBoard.jspa?rapidView=1493&projectKey=RAS&view=detail&selectedIssue=RAS-915

Fix deprecated set output

---

Pipfile.lock
_infra/helm/collection-instrument/Chart.yaml

```
pipenv update flask-cors flask-httpauth
pipenv update --dev flask-testing
```
To resolve 3.1.2 jinja2 security alert

Bump flask packages to upgrade jinja2 to 3.1.3 to fix security alert

---

Pipfile.lock
_infra/helm/collection-instrument/Chart.yaml

To fix security alert by bumping dev package idna from 3.6 -> 3.7

Upgrade requests-mock to fix idna security alert

---

.github/workflows/main.yml
Makefile
Pipfile.lock
README.md
_infra/helm/collection-instrument/Chart.yaml
docker-compose.yml
tox.ini

Updating references to the now removed `docker-compose` in favour of `docker compose`
recreated from https://github.com/ONSdigital/ras-collection-instrument/pull/334
Make sure the tests run properly
[RAS-1238](https://jira.ons.gov.uk/browse/RAS-1238)

recreate with bot signing

---

.github/workflows/main.yml
.gitignore
_infra/helm/collection-instrument/Chart.yaml
_infra/helm/collection-instrument/values.yaml

GAR migration for collection instrument.
Deploy this to your environment, setting configBranch to `ras-1480-collection-instrument-gar-migration`. The deployment will hang until you replace the image in the YAML with `europe-west2-docker.pkg.dev/ons-ci-rmrasbs/images/collection-instrument:pr-348`.
Use helm commands to delete the service, deployment, and external secret, then redeploy the service in your environment.
[Card](https://jira.ons.gov.uk/browse/RAS-1480)

collection-instrument gar migration

---

_infra/helm/collection-instrument/Chart.yaml
application/controllers/registry_instrument.py
application/controllers/registry_instrument_validator.py
application/controllers/sql_queries.py
application/models/models.py
application/views/registry_instrument_view.py
migrations/versions/b730b3a81f72_add_registry_instrument_table.py
openapi.yaml
run.py
tests/controllers/test_registry_instrument.py
tests/controllers/test_registry_instrument_validator.py
tests/test_data/registry_instrument.json
tests/test_data/registry_instruments.json
tests/views/test_registry_instrument_view.py

Introduction of the new registry instrument resource.
>_Due to the complications detailed under [OPTION 1](https://github.com/ONSdigital/ras-rm-documentation/tree/main/spike/cir-integration#option-1) in the original design proposal, this solution does NOT address the already complex and redundant RASRM survey scoped collection instrument relationships. Indeed, this solution to introduce CIR deliberately sidesteps that data model, and introduces selected CIR resources, named `registry-instrument`, and keyed on RASRM UUID references, and explicitly operated on (CRUD) by its own API._
>_The consequence of this is loose data integrity, where the foreign and primary keys of the integer ID sequences for surveys, exercises and instruments are not used (as these are provided solely by survey …

Introduce registry-instrument resource
